---
title: Jogo Pacman
---
classDiagram
        class Jogo{
            int pontuacao
        }
        class Tabuleiro{
             fantasmas
             pacman
        }
        class Pacman{
        }
        class Fantasma{
            <<Interface>>
        }
        class Blinky{
        }
        class Pinky{
        }
        class Inky{
        }
        class Clyde{
        }
        class Ponto{
            <<Abstract>>
        }
        class PontoComum{
        }
        class PontoSpecial{
        }
        class Obstaculo{
            <<Abstract>>
        }
        class ObstaculoComum{
        }
        class ObstaculoSpecial{
        }
        class CriadorTabuleiro{
            <<Abstract>>
            criaPontos()
            criaObstaculos()
        }
        class CriadorTabuleiroComum{
            criaPontos()
            criaObstaculos()
        }
        class CriadorTabuleiroSpecial{
            criaPontos()
            criaObstaculos()
        }
        Jogo "1" *-- "1" Tabuleiro
        Tabuleiro "1" *-- "1" Pacman
        Tabuleiro "1" *-- "4" Fantasma
        Tabuleiro "1" *-- "*" Ponto
        Tabuleiro "1" *-- "*" Obstaculo
        Fantasma <|.. Blinky
        Fantasma <|.. Pinky
        Fantasma <|.. Inky
        Fantasma <|.. Clyde
        Ponto <|-- PontoComum
        Ponto <|-- PontoSpecial
        Obstaculo <|-- ObstaculoComum
        Obstaculo <|-- ObstaculoSpecial
        CriadorTabuleiro <|-- CriadorTabuleiroComum
        CriadorTabuleiroComum --> PontoComum
        CriadorTabuleiroComum --> ObstaculoComum
        CriadorTabuleiro <|-- CriadorTabuleiroSpecial
        CriadorTabuleiroSpecial --> PontoSpecial
        CriadorTabuleiroSpecial --> ObstaculoSpecial

        
        

            


